### PR TITLE
Fix rounding on float16 conversions

### LINKED ISSUE #8366: Flaky test: `chainerx_tests/unit_tests/routines_tests/test_arithmetic.py::test_IRemainder`
Occurred in #8364

https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2391/TEST=CHAINERX_chainerx-py3,label=mn1-p100/

`15:28:57 FAIL ../../../repo/tests/chainerx_tests/unit_tests/routines_tests/test_arithmetic.py::test_IRemainder_param_206_{in_dtypes=('float16', 'float32'), in_shapes=((2, 3), (2, 3)), input_lhs=2, input_rhs=2, out_dtype='float32', skip_backward_test=True, skip_double_backward_test=True}[native:0]`

```
15:28:57 E       chainer.testing.function_link.FunctionTestError: Outputs do not match the expected values.
15:28:57 E       Indices of outputs that do not match: 0
15:28:57 E       Expected shapes and dtypes: (2, 3):float16
15:28:57 E       Actual shapes and dtypes:   (2, 3):float16
15:28:57 E       
15:28:57 E       
15:28:57 E       Error details of output [0]:
15:28:57 E       
15:28:57 E       Not equal to tolerance rtol=0.001, atol=0.001
15:28:57 E       
15:28:57 E       Mismatch: 16.7%
15:28:57 E       Max absolute difference: 0.001953
15:28:57 E       Max relative difference: 0.012344
15:28:57 E        x: array([[-1.083 , -1.611 ,  2.746 ],
15:28:57 E              [ 0.1562,  0.858 ,  2.852 ]], dtype=float16)
15:28:57 E        y: array([[-1.083 , -1.611 ,  2.746 ],
15:28:57 E              [ 0.1582,  0.858 ,  2.852 ]], dtype=float16)
15:28:57 E       
15:28:57 E       assert_allclose failed: 
15:28:57 E         shape: (2, 3) (2, 3)
15:28:57 E         dtype: float16 float16
15:28:57 E         i: (1, 0)
15:28:57 E         x[i]: 0.15625
15:28:57 E         y[i]: 0.158203125
15:28:57 E         relative error[i]: 0.0123443603515625
15:28:57 E         absolute error[i]: 0.001953125
15:28:57 E         relative tolerance * |y[i]|: 0.000158203125
15:28:57 E         absolute tolerance: 0.001
15:28:57 E         total tolerance: 0.001158203125
15:28:57 E       x: [[-1.083  -1.611   2.746 ]
15:28:57 E           [ 0.1562  0.858   2.852 ]]
15:28:57 E       y: [[-1.083  -1.611   2.746 ]
15:28:57 E           [ 0.1582  0.858   2.852 ]]
```

### PR DESCRIPTION
**Pull request by emcastillo**
Closes  #8366 

When casting a Chainerx array in the native backend to float16 the float16 code differs subtly from the numpy one in the rounding of elements. 

https://github.com/numpy/numpy/blob/1f8fb2ca31a7f41a23c60e4ffcb38b3e0cb201f7/numpy/core/src/npymath/halffloat.c#L339-L347

This caused the IRemainder test to yield 150 failures for 1 million runs.
After fixing the number went down to 0.

The fp64 to fp16 case has been similarly fixed to match the numpy logic as some of the calculations were different and it was not clear where did they come from.

### CODE REVIEW

File: chainerx_cc/chainerx/float16.cc [hunk 1]
```diff
@@ -63,7 +63,9 @@ uint16_t FloatbitsToHalfbits(uint32_t f) {
         uint32_t f_sig = (0x00800000U + (f & 0x007fffffU)) >> (113 - f_exp);
 
         // Handle rounding by adding 1 to the bit beyond half precision
-        f_sig += 0x00001000U;
+        if (((f_sig&0x00003fffu) != 0x00001000u) || (f&0x000007ffu)) {
```
Comment (niboshi) [inline chainerx_cc/chainerx/float16.cc]: Please add spaces to match the style of surrounding code.

File: chainerx_cc/chainerx/float16.cc [hunk 2]
```diff
@@ -75,7 +77,10 @@ uint16_t FloatbitsToHalfbits(uint32_t f) {
     uint16_t h_exp = static_cast<uint16_t>((f_exp - 0x38000000U) >> 13);
 
     // Handle rounding by adding 1 to the bit beyond half precision
-    uint32_t f_sig = (f & 0x007fffffU) + 0x00001000U;
+    uint32_t f_sig = (f & 0x007fffffU);
```
Comment (niboshi) [inline chainerx_cc/chainerx/float16.cc]: Remove redundant parentheses.

File: chainerx_cc/chainerx/float16.cc (hunk 1 above)
Comment (niboshi) [inline chainerx_cc/chainerx/float16.cc]: Use capital letters for integral suffixes.

**Comment by niboshi** [comment]
Also please write tests.

**Comment by emcastillo** [comment]
I added an initial try for testing it, it is for the float32 case,
If its ok I will extend it to take the float64 in account too.

Since this is a numpy related change I was doubting on how to do the testing.
The two alternatives that I though was to explicitly test if a number was not rounded, or
add a new python test which compares chainerx and numpy type castings. I went for the first one since the scope seems broader and the later its extensively tested in the routines.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.
